### ISSUE TITLE
Set node contraints for song and score in rdpc

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#470]
need to:
- define resource
- set song to run on infra nodes not workflow ones
- add tolerations

```
 nodeSelector:
    type: infra
tolerations:
  - effect: NoSchedule
    key: type
    operator: Equal
    value: infra
```

https://github.com/icgc-argo/rdpc-infra/pull/110

- [x] SONG
- [x] INTERMEDIATE SONG
- [ ] SCORE

Score - the release has been updated with the node selector values but the chart does not support node selector, the chart needs to be updated. https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/roadmap/552
